package com.merge.mergedatingapp.usersTest;

import org.junit.jupiter.api.Test;
import com.merge.mergedatingapp.users.User;
import java.time.Instant;

import static org.junit.jupiter.api.Assertions.*;

class UserTest {

    @Test
    void builder_setsAllFieldsCorrectly() {
        Instant created = Instant.parse("2025-01-01T12:00:00Z");

        User u = User.builder()
                .id(null) // usually generated by JPA
                .username("TestUser")
                .passwordHash("hashed-pass1")
                .createdAt(created)
                .build();

        assertNull(u.getId());
        assertEquals("TestUser", u.getUsername());
        assertEquals("hashed-pass1", u.getPasswordHash());
        assertEquals(created, u.getCreatedAt());
    }

    @Test
    void defaultConstructor_hasNonNullCreatedAt() {
        User u = new User();
        // Lombok @Getter/@Setter give us accessors
        assertNotNull(u.getCreatedAt(), "createdAt should default to a non-null value");
    }

    @Test
    void settersAndGetters_workAsExpected() {
        User u = new User();
        Instant created = Instant.parse("2023-12-31T23:59:59Z");

        u.setUsername("TestUser2");
        u.setPasswordHash("hashed-pass2");
        u.setCreatedAt(created);

        assertEquals("TestUser2", u.getUsername());
        assertEquals("hashed-pass2", u.getPasswordHash());
        assertEquals(created, u.getCreatedAt());
    }
}
